### ISSUE TITLE
Fix doc duplication in README and quickstart

### ISSUE THREAD

**Issue by kimdhamilton** [digital-certificates/cert-viewer#26]
Previously we had difficulties with referencing README content from the docs folder. However, that was when we had the additional constraint of integrating sphinx and markdown. Now that we're using mkdocs, this may be easier.

Fix and update in all repos

**Comment by DennisCC** [comment]
K. Thx

On Monday, 20 June 2016, Kim (Hamilton) Duffy <notifications@github.com>
wrote:

> Previously we had difficulties with referencing README content from the
> docs folder. However, that was when we had the additional constraint of
> integrating sphinx and markdown. Now that we're using mkdocs, this may be
> easier.
>
> Fix and update in all repos
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/digital-certificates/cert-viewer/issues/26>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ARxeyv1uQKl2N7M1zftOHKC7BYwdn7d8ks5qNvtRgaJpZM4I6Grk>
> .
>


-- 
________________________________
Dennis Carter-Chand, MBA
Email: dennis@carterchand.com
Phone, Text: +1-647-515-7961
LinkedIn: www.linkedin.com/in/dcarterchand

**Comment by kimdhamilton** [comment]
fixed in relevant projects: cert-viewer and cert-issuer
